### ISSUE TITLE
Get entire list of entries

### ISSUE THREAD

**Issue by CryADsisAM** [dance2die/MyAnimeListSharp#2]
The only thing missing is the ability to download the **entire list** of either anime or manga entries. Are you planning to implement this? or have I missed it somewhere...

**Comment by dance2die** [comment]
Hi @CryADsisAM.

At this point, I don't have a plan to implement that feature 
because I don't know how/where to get entire list of anime or manga.

Would you let me know if you happen to find where to get the list?
I will implement that feature in the future release.
