### ISSUE TITLE
All Calls to MAL service return HTTP 403 (Forbidden)

### ISSUE THREAD

**Issue by onilink128** [dance2die/MyAnimeListSharp#3]
I believe the error occurs because MAL changed the Web Service and only accepting calls through https.

Sorry for my bad english.

**Comment by dance2die** [comment]
@onilink128 Thanks Rodrigo. Thank you for the issue report. I will take a look at it.

**Comment by darth2499** [comment]
Same here, would be appreciative if this can be fixed.

**Comment by dance2die** [comment]
@darth2499 I'm making changes to the library.
It seems like HTTPS was not the only breaking change made to the MAL API.
I have to modify Anime/Manga Value XML generations as well.

Out of 149 tests, 4 are failing, and they have something to do with adding a new manga/anime.

**Comment by dance2die** [comment]
@darth2499 @onilink128
I fixed all issues and released a new version of Nuget package (GitHub source is up to date now) version 1.3.2 on https://www.nuget.org/packages/MyAnimeListSharp
