### ISSUE TITLE
InvalidOperationException by anime Search

### ISSUE THREAD

**Issue by kirillVv** [dance2die/MyAnimeListSharp#4]
Hello ,

i'm pretty new to programming and right now i try to make my own small anime list. Got a small problem and can't figure out how to solve it , + not realy sure where to ask it.

I have made so that when i try to search for something and there is not such thing i get a message 

` if (string.IsNullOrWhiteSpace(response))
    {
         MessageBox.Show("No such thing");
    }`

but after that when i try to search for something else i I get an 

`InvalidOperationException: Operation is not valid due to the current state of the object. In MyAnimeListSharp.Core.MyAnimeListMethods.<GetResponseTextAsync>d__5.MoveNext()` 

And after i close this error message i can search normaly again.

If you have time,  i would appreciate if you could give me some tips on how to handle this error.

Thank you in advance !!

**Comment by dance2die** [comment]
@kirillVv Hi, there.

Do you have a stack trace I can take a look at?
And also the part where you call the search method and assign the response would be helpful.

**Comment by kirillVv** [comment]
@dance2die 

I have made an stack question here : http://stackoverflow.com/questions/41925309/invalidoperationexception-by-search

**Comment by kirillVv** [comment]
@dance2die  I'm sorry, i don't know how to use Stack trace :( , but here is the Search method code.


       `private async void tbSearch_KeyDown(object sender, KeyEventArgs e)
        {
            ICredentialContext credential = new CredentialContext
            {
                UserName = username,
                Password = password
            };

            if (e.KeyCode == Keys.Enter)
            {
                if (string.IsNullOrEmpty(tbSearch.Text))
                {
                    MessageBox.Show("Nothing to Search for.....");
                }
                else
                {
                    string response;

                    var asyncAnimeSearch = new AnimeSearchMethodsAsync(credential);
                    response = await asyncAnimeSearch.SearchAsync(tbSearch.Text); // Error occurs here when i try to search again . Error disappears when i try to search after it.

                    if (username == "" && password == "")
                    {
                        MessageBox.Show("Add account");
                    }
                    else if (string.IsNullOrWhiteSpace(response)) // After this the error occurs when i try to search again.
                    {
                        MessageBox.Show("No such entry");
                    }
                    else
                    {   // Add response to ListView

                        lvAnimeResult.BeginUpdate();
                        lvAnimeResult.Items.Clear();

                        XmlDocument doc = new XmlDocument();

                        doc.LoadXml(response);

                        XmlNodeList list = doc.SelectNodes("/anime/entry");

                        foreach (XmlNode node in list)
                        {
                            string series_id = node["id"].InnerText;
                            string series_title = node["title"].InnerText;
                            string series_title_english = node["english"].InnerText;
                            string series_episodes = node["episodes"].InnerText;
                            string series_score = node["score"].InnerText;
                            string series_type = node["type"].InnerText;
                            string series_status = node["status"].InnerText;
                            string series_start_date = node["start_date"].InnerText;
                            string series_end_date = node["end_date"].InnerText;
                            string series_image = node["image"].InnerText;

                            string[] lvElements = new string[11];
                            ListViewItem items;

                            lvElements[0] = series_title;
                            lvElements[1] = series_type;
                            lvElements[2] = series_episodes;
                            lvElements[3] = series_score;
                            lvElements[4] = series_id;
                            lvElements[5] = series_title_english;
                            lvElements[6] = series_status;
                            lvElements[7] = series_start_date;
                            lvElements[8] = series_end_date;
                            lvElements[9] = series_image;

                            items = new ListViewItem(lvElements);
                            lvAnimeResult.Items.Add(items);
                            lvAnimeResult.EndUpdate();
                        }
                    }
                }
            }
        }`

**Comment by dance2die** [comment]
@kirillVv 
I created a little demo using your source but I am not able to replicate the error (https://github.com/dance2die/Demo.MyAnimeListFormDemo)

What version of MyAnimeListSharp are you using? The latest version is 1.3.2.
If you had installed the library using "Nuget", you can open Nuget package manager (right click on the project that uses the library -> Manage Nuget Package), click on "Installed" tab, and click on "MyAnimeListSharp".

If the version you installed is 1.3.2, then would it be possible to share the full source on GitHub? 

Lastly, what is the search term you used to search?

**Comment by kirillVv** [comment]
I have added the search form to github. 
( https://github.com/kirillVv/AnimeSearch/tree/master/AnimeSearch ).

I have accidentally got that error by miss typing anime name. I wrote 'school-days' instead of 'school-live' and then have searched for 'school-live'

**Comment by dance2die** [comment]
@kirillVv Hi.

Thank you for sharing the code. (I forked it test it on https://github.com/dance2die/AnimeSearch)

I was able to reproduce the issue and fixed it.
I just released a new version on Nuget (v 1.3.3).
Please update the nuget package and try again.

**Comment by kirillVv** [comment]
@dance2die  thank you for fixing it and thank you for good and simple library :D.

Everything works like a charm.

**Comment by dance2die** [comment]
@kirillVv You're welcome. And thank you for reporting. 

Closing the issue....
