### ISSUE TITLE
Invalid Score by MAL Update

### ISSUE THREAD

**Issue by kirillVv** [dance2die/MyAnimeListSharp#6]
Good day,

it's me again. Today i was trying to implement the update function to my small program and found a wierd thing. When you update the `Score` in `AnimeValues` , it updates the score by previous value . So when i put  `Score.MasterPiece`  on MAL it shows as `Great` or `Score.Appalling` is actualy `-`  ( nothing ) on MAL.

here is my code if you need it : 

            var AnimeId = Convert.ToInt32(tbWatchingID.Text);
            var EpsWatched = Convert.ToInt16(tbWatchingEpWatched.Text);
            var PersScore = Convert.ToInt32(tbPersScoreWatch.Text);
            
            var methods = new AnimeListMethods(credential);
            

            if (PersScore == 0 || PersScore == 1)
            {
                var animeValues = new AnimeValues
                {
                   Episode = EpsWatched,
                   Score = Score.Appalling
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
                
            }
            else if (PersScore == 2)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Horrible
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 3)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.VeryBad
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 4)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Bad
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 5)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Average
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 6)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Fine
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 7)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Good
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 8)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.VeryGood
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if (PersScore == 9)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.Great
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }
            else if(PersScore == 10)
            {
                var animeValues = new AnimeValues
                {
                    Episode = EpsWatched,
                    Score = Score.MasterPiece
                };

                var response = methods.UpdateAnime(AnimeId, animeValues);
            }

            MessageBox.Show("Updated");
       

Thank you for your time !

**Comment by dance2die** [comment]
@kirillVv Hi there.
I will check it out today and get back to you.

**Comment by dance2die** [comment]
@kirillVv I've fixed the issue and released a new version 1.3.4 to Nuget.
Please update the Nuget package and it'd work.

The issue was that, I didn't initialize the Score.Appalling to 1 so the score was starting from 0, not from 1.
Now I've initialized the first value to 1, Score.MasterPiece is now initialized to 10

https://github.com/dance2die/MyAnimeListSharp/blob/master/Project.MyAnimeList/Project.MyAnimeList/Enums/Score.cs

**Comment by dance2die** [comment]
@kirillVv 
Also, you can shorten  your code and make it more maintainable, by simply casting the persScore to Score.

```csharp
            AnimeValues animeValues = new AnimeValues
            {
                Episode = epsWatched,
                Score = (Score)persScore
            };
```

Full source is available [here](https://github.com/dance2die/AnimeSearch/blob/master/UpdateAnimeValueConsole/Program.cs)(it'd be much shorter than you expected~).

**Comment by kirillVv** [comment]
Everything works as expected !!  And big thanks for showing me the short version ! :D

**Comment by dance2die** [comment]
@kirillVv Thank you for your bug report again. I really appreciate it~
And have fun programming!
